# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config
# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "djhqrlzaummgwbpktfbu"

[auth.external.google]
enabled = true
client_id = "358067531158-qevoupr3ds9p8p4stvqqh6d5fpqi4ti5.apps.googleusercontent.com"
secret = "env(SUPABASE_AUTH_EXTERNAL_GOOGLE_CLIENT_SECRET)"
skip_nonce_check = false
